/* =====================================================================
   Engine Build Tasks — one hands-on task per lesson. Done in order, they
   build "MiniEngine": a small, Unity/Unreal-style DirectX 11 engine with a
   GameObject–Component system. main.js injects each task into its lesson;
   tasks.html aggregates them all into the Build Tracker.
   `id` matches the curriculum lesson id (module-number + "-" + slug).
   diff: Warm-up | Easy | Core | Challenge | Boss
   ===================================================================== */
window.TASKS = [
  // Module 00 — Getting Started
  { id:'00-what-is-cpp', builds:'Project', diff:'Warm-up', title:'Plan MiniEngine',
    brief:'Write a short goal doc for the engine you\'ll build: a windowed DirectX 11 app that renders 3D objects through a GameObject–Component system, like a tiny Unity.',
    deliverable:'A GOALS.txt naming your engine and its one-sentence purpose.' },
  { id:'00-how-cpp-works', builds:'Project', diff:'Warm-up', title:'Predict the build',
    brief:'List the pieces your engine will compile and link: an Engine static library, a Sandbox executable, and the DirectX import libs (d3d11.lib).',
    deliverable:'A note listing your translation units and the libraries you\'ll link.' },
  { id:'00-install-visual-studio', builds:'Setup', diff:'Warm-up', title:'Verify your toolchain',
    brief:'Confirm Visual Studio has the "Desktop development with C++" workload and a Windows 10/11 SDK — the SDK is what ships DirectX.',
    deliverable:'A checklist confirming the C++ workload and Windows SDK are installed.' },
  { id:'00-first-program', builds:'Project', diff:'Easy', title:'Create the Sandbox project',
    brief:'Make a Console App named Sandbox that prints your engine\'s boot banner.',
    deliverable:'A program that prints e.g. "MiniEngine booting…".' },
  { id:'00-build-run-debug', builds:'Setup', diff:'Easy', title:'Debug a breakpoint',
    brief:'Set a breakpoint in main, run under the debugger, and inspect a variable — you\'ll lean on this when the render loop misbehaves.',
    deliverable:'Confirm you can hit a breakpoint, step, and watch a value.' },
  { id:'00-project-anatomy', builds:'Project', diff:'Core', title:'Split into Engine + Sandbox',
    brief:'Reorganize into an Engine static-library project and a Sandbox .exe that links it; move a Hello() function into the Engine.',
    deliverable:'Two projects where Sandbox calls Engine::Hello().' },

  // Module 01 — C++ Fundamentals
  { id:'01-variables-types', builds:'Foundation', diff:'Easy', title:'Engine config constants',
    brief:'Define typed constants for your engine: window width, height, target FPS, and title.',
    deliverable:'A Config.h with constexpr values.' },
  { id:'01-constants-io', builds:'Foundation', diff:'Easy', title:'Boot log',
    brief:'Print a formatted startup log built from your config constants.',
    deliverable:'Output like "MiniEngine 1280x720 @ 60 FPS".' },
  { id:'01-operators', builds:'Foundation', diff:'Easy', title:'Frame-time math',
    brief:'From a frame count and elapsed seconds, compute average FPS and average frame time in ms — mind integer vs float division.',
    deliverable:'A function that prints both correctly.' },
  { id:'01-conditionals', builds:'Foundation', diff:'Easy', title:'Quality preset picker',
    brief:'Use if/switch to map a numeric score to a quality preset (Low/Medium/High).',
    deliverable:'A SelectQuality(int) function.' },
  { id:'01-loops', builds:'Foundation', diff:'Core', title:'The proto game loop',
    brief:'Write a loop that runs a handful of fake frames, printing "Frame N: update, render" — the shape of your real loop.',
    deliverable:'A loop skeleton that runs N frames.' },
  { id:'01-functions', builds:'Math', diff:'Core', title:'Engine math helpers',
    brief:'Implement Clamp, Lerp, Min/Max and DegreesToRadians as reusable functions.',
    deliverable:'A MathUtils.h/.cpp with these helpers.' },
  { id:'01-scope-lifetime', builds:'Foundation', diff:'Easy', title:'Keep frames stateless',
    brief:'Write a per-frame function whose locals are created and destroyed each call; comment where each dies so no state leaks between frames.',
    deliverable:'A commented example proving no cross-frame leakage.' },

  // Module 02 — Data & Memory
  { id:'02-arrays-vectors', builds:'Scene', diff:'Easy', title:'The object list',
    brief:'Store a list of object names/ids in a std::vector and iterate it — your scene will be a vector of GameObjects.',
    deliverable:'A vector you fill and loop over.' },
  { id:'02-strings', builds:'Resources', diff:'Easy', title:'Asset-path helpers',
    brief:'Write helpers to pull the filename and extension out of an asset path string.',
    deliverable:'PathUtils functions (GetFileName, GetExtension).' },
  { id:'02-references', builds:'Scene', diff:'Core', title:'Update by reference',
    brief:'Write UpdatePosition(Position& p, float dt) that moves a struct in place — no copies.',
    deliverable:'A Position struct + a by-reference update function.' },
  { id:'02-pointers', builds:'Scene', diff:'Core', title:'The owner back-pointer',
    brief:'Give a Component a raw pointer back to its owner; set it and read through it — exactly how components find their GameObject.',
    deliverable:'A minimal Owner/Component pointer demo.' },
  { id:'02-dynamic-memory', builds:'Scene', diff:'Core', title:'Heap objects (then fix the leak)',
    brief:'Allocate an object with new, use it, free it with delete; introduce a leak and fix it — motivation for smart pointers next module.',
    deliverable:'A leak-then-fix demo.' },
  { id:'02-structs-enums', builds:'Renderer', diff:'Core', title:'Vertex & Color',
    brief:'Define your engine\'s Vertex (position, and later normal/uv) and a Color struct, plus an enum class for primitive topology.',
    deliverable:'A Vertex.h with your vertex format.' },
  { id:'02-multiple-files', builds:'Project', diff:'Core', title:'Header/source discipline',
    brief:'Split MathUtils and Vertex into clean .h/.cpp with #pragma once and expose them from the Engine lib.',
    deliverable:'Organized headers the Sandbox can include.' },

  // Module 03 — Object-Oriented C++
  { id:'03-classes', builds:'Platform', diff:'Core', title:'Timer class',
    brief:'Write a Timer class that reports the delta time between ticks — your game loop will drive everything with it.',
    deliverable:'A Timer.h/.cpp (Start, Tick → seconds).' },
  { id:'03-constructors-raii', builds:'Foundation', diff:'Core', title:'An RAII resource holder',
    brief:'Write a class that acquires a resource in its constructor and releases it in its destructor — the pattern your GPU resources will follow.',
    deliverable:'A ScopedResource demo that cleans up automatically.' },
  { id:'03-encapsulation', builds:'Scene', diff:'Core', title:'Encapsulate the Transform',
    brief:'Make a Transform class with private position/rotation/scale and public const getters/setters.',
    deliverable:'Transform.h (version 1).' },
  { id:'03-inheritance', builds:'Scene', diff:'Core', title:'The Component base class',
    brief:'Define a Component base class holding an owner pointer, ready for derived components to extend.',
    deliverable:'A Component.h base class.' },
  { id:'03-polymorphism', builds:'Scene', diff:'Challenge', title:'Update through base pointers',
    brief:'Derive two demo components (e.g. Rotator, Logger) that override a virtual OnUpdate(dt); store them as base pointers and update all in a loop. Give Component a virtual destructor.',
    deliverable:'A polymorphic update loop over mixed components.' },
  { id:'03-operator-overloading', builds:'Math', diff:'Core', title:'Vector3 operators',
    brief:'Implement Vector3 with +, -, * (by scalar), ==, plus Dot() and Length().',
    deliverable:'A Vector3.h with operators.' },
  { id:'03-templates', builds:'Scene', diff:'Challenge', title:'GetComponent<T>()',
    brief:'Write a template that scans a component list and returns the first component of type T (use dynamic_cast).',
    deliverable:'A working GetComponent<T>() template.' },
  { id:'03-smart-pointers', builds:'Scene', diff:'Core', title:'Own components with unique_ptr',
    brief:'Change your component container to vector<unique_ptr<Component>> and add components with make_unique.',
    deliverable:'Components owned by smart pointers, no manual delete.' },
  { id:'03-stl', builds:'Resources', diff:'Core', title:'A tiny resource cache',
    brief:'Use unordered_map<string, shared_ptr<...>> to return a cached resource or insert a new one.',
    deliverable:'A ResourceCache sketch keyed by name.' },

  // Module 04 — Math for Graphics
  { id:'04-coordinate-systems', builds:'Math', diff:'Easy', title:'Choose your handedness',
    brief:'Document that MiniEngine uses left-handed coordinates (DirectX) and note the space chain local → world → view → clip.',
    deliverable:'A short convention note in your Math module.' },
  { id:'04-vectors', builds:'Math', diff:'Core', title:'Complete Vector3 / Vector4',
    brief:'Add Normalize, Cross and distance to Vector3, and add a Vector4; verify Length and Normalize.',
    deliverable:'Finished Vector3 and Vector4 types.' },
  { id:'04-dot-cross', builds:'Math', diff:'Core', title:'Normals & facing',
    brief:'Use the dot product to test whether a surface faces a light direction, and the cross product to compute a triangle\'s normal.',
    deliverable:'A ComputeNormal() plus a facing test.' },
  { id:'04-matrices', builds:'Math', diff:'Challenge', title:'Matrix4 transforms',
    brief:'Build a Matrix4 (or wrapper) supporting identity, translation, rotation, scale and multiply; confirm the T·R·S order.',
    deliverable:'A Matrix4 you can compose transforms with.' },
  { id:'04-directxmath', builds:'Math', diff:'Core', title:'Build an MVP',
    brief:'With DirectXMath, build world, view (LookAtLH) and projection (PerspectiveFovLH) matrices and combine them.',
    deliverable:'A BuildMVP() returning a stored XMFLOAT4X4.' },

  // Module 05 — Windows & the Game Loop
  { id:'05-win32-window', builds:'Platform', diff:'Core', title:'Open the engine window',
    brief:'Create a real Win32 window titled with your engine name and sized from your config.',
    deliverable:'A window that opens and stays up.' },
  { id:'05-message-loop', builds:'Platform', diff:'Core', title:'Handle close & keys',
    brief:'Add a WndProc that quits on WM_DESTROY and logs keys on WM_KEYDOWN (ESC closes); pump messages with PeekMessage.',
    deliverable:'A window that responds to input and closes cleanly.' },
  { id:'05-game-loop', builds:'Platform', diff:'Challenge', title:'The real delta-time loop',
    brief:'Combine the window and Timer into a loop: poll messages → update(dt) → render (stub); print the FPS.',
    deliverable:'Your engine\'s beating heart — a stable frame loop.' },

  // Module 06 — DirectX 11 Foundations
  { id:'06-graphics-pipeline', builds:'Renderer', diff:'Easy', title:'Map the pipeline',
    brief:'For your engine, note what each pipeline stage handles: IA feeds vertices, the VS transforms them, the PS colors pixels.',
    deliverable:'A one-page pipeline map for MiniEngine.' },
  { id:'06-d3d11-init', builds:'Renderer', diff:'Challenge', title:'Bring up Direct3D 11',
    brief:'Initialize the device, context and swap chain for your window and create the render target view.',
    deliverable:'A Renderer::Init() that succeeds (check every HRESULT).' },
  { id:'06-clear-screen', builds:'Renderer', diff:'Core', title:'Clear to your brand color',
    brief:'Each frame, set the viewport, clear the back buffer to a chosen color, and Present.',
    deliverable:'A window that repaints a solid color every frame.' },
  { id:'06-first-triangle', builds:'Renderer', diff:'Challenge', title:'Draw a triangle',
    brief:'Create a vertex buffer of three colored vertices and Draw it.',
    deliverable:'A triangle on screen.' },
  { id:'06-shaders-hlsl', builds:'Renderer', diff:'Challenge', title:'Author your shaders',
    brief:'Write and compile a vertex + pixel shader for colored vertices and bind them to the pipeline.',
    deliverable:'A shaders.hlsl plus the C++ that loads it.' },
  { id:'06-input-layouts', builds:'Renderer', diff:'Core', title:'Describe your Vertex',
    brief:'Create the input layout that matches your Vertex struct and the VS input semantics, then bind it.',
    deliverable:'An input layout wired to your triangle.' },
  { id:'06-constant-buffers', builds:'Renderer', diff:'Core', title:'A per-object constant buffer',
    brief:'Add a cbuffer (register b0) for a transform/color, create it, and update it each frame.',
    deliverable:'A constant buffer feeding data to your shader.' },
  { id:'06-transformations-mvp', builds:'Renderer', diff:'Challenge', title:'Go perspective 3D',
    brief:'Upload the MVP matrix (transposed for HLSL) via the constant buffer and transform the vertex in the VS.',
    deliverable:'Your geometry rendered in true 3D perspective.' },
  { id:'06-index-buffers', builds:'Renderer', diff:'Core', title:'Draw a cube',
    brief:'Define 8 vertices and 36 indices and render the cube with DrawIndexed.',
    deliverable:'A cube on screen.' },
  { id:'06-depth-buffer', builds:'Renderer', diff:'Core', title:'Add depth & culling',
    brief:'Create and bind a depth-stencil view, clear it each frame, and enable back-face culling so the cube renders solidly.',
    deliverable:'A correctly depth-sorted cube.' },
  { id:'06-textures', builds:'Renderer', diff:'Challenge', title:'Texture the cube',
    brief:'Add UVs, create a texture + shader-resource view + sampler, and sample it in the pixel shader.',
    deliverable:'A textured cube.' },
  { id:'06-camera', builds:'Renderer', diff:'Challenge', title:'Fly the camera',
    brief:'Add a camera that builds view + projection and moves with WASD and the mouse; feed it into the constant buffer.',
    deliverable:'Free navigation around your cube.' },

  // Module 07 — Engine Architecture
  { id:'07-what-is-an-engine', builds:'Architecture', diff:'Easy', title:'List your subsystems',
    brief:'Enumerate the subsystems MiniEngine will own — Window, Renderer, Input, Time, Scene — and each one\'s job.',
    deliverable:'A subsystem responsibilities note.' },
  { id:'07-engine-subsystems', builds:'Architecture', diff:'Core', title:'Application skeleton',
    brief:'Sketch the Application/Engine class that owns the subsystems and exposes Init / Run / Shutdown.',
    deliverable:'An Application.h skeleton.' },
  { id:'07-gameobject-component', builds:'Scene', diff:'Core', title:'Design GameObject–Component',
    brief:'Define the GameObject and Component interfaces: a GameObject has a Transform plus components; components have OnUpdate/OnRender.',
    deliverable:'Interface headers for GameObject and Component.' },
  { id:'07-actor-component', builds:'Architecture', diff:'Easy', title:'Compare the models',
    brief:'Map Unity\'s GameObject/Component to Unreal\'s Actor/Component and state which one MiniEngine follows (and why).',
    deliverable:'A short comparison note.' },
  { id:'07-ecs', builds:'Architecture', diff:'Easy', title:'OOP vs ECS decision',
    brief:'Justify using the GameObject–Component model for MiniEngine now, and note where an ECS would pay off later.',
    deliverable:'A 2–3 sentence architecture decision.' },
  { id:'07-scene-graph', builds:'Scene', diff:'Challenge', title:'Parent–child transforms',
    brief:'Extend Transform with a parent pointer and GetWorldMatrix() = parent.world × local so moving a parent moves its children.',
    deliverable:'A Transform hierarchy that propagates.' },
  { id:'07-resource-management', builds:'Resources', diff:'Core', title:'A ResourceManager',
    brief:'Build a ResourceManager that loads-or-returns cached meshes/textures via shared_ptr, keyed by path.',
    deliverable:'A caching ResourceManager class.' },
  { id:'07-input-time-systems', builds:'Platform', diff:'Core', title:'Input & Time services',
    brief:'Wrap keyboard/mouse into an Input service (IsKeyDown / IsKeyPressed / mouse delta) and expose a Time service (DeltaTime / TotalTime).',
    deliverable:'Input.h and Time.h services.' },

  // Module 08 — Build Your Engine
  { id:'08-project-setup', builds:'Project', diff:'Core', title:'Lay out the engine',
    brief:'Create the Engine library folders (Core, Renderer, Scene, Math, Platform) and the Sandbox project, with a precompiled header.',
    deliverable:'The full engine project skeleton.' },
  { id:'08-application-window', builds:'Platform', diff:'Challenge', title:'Application + Window classes',
    brief:'Implement Window (owns the HWND) and Application (the Run loop with virtual OnUpdate/OnRender); have Sandbox subclass Application.',
    deliverable:'An app that opens a window and ticks its loop.' },
  { id:'08-renderer-abstraction', builds:'Renderer', diff:'Challenge', title:'The Renderer class',
    brief:'Wrap D3D11 in a Renderer with BeginFrame / Clear / EndFrame and ComPtr members; the Application drives it.',
    deliverable:'A Renderer subsystem hiding raw D3D calls.' },
  { id:'08-math-library', builds:'Math', diff:'Core', title:'Engine math library',
    brief:'Consolidate Vector3/4, Matrix and transform helpers into one Math module the whole engine uses.',
    deliverable:'A reusable Math module.' },
  { id:'08-mesh-model', builds:'Renderer', diff:'Challenge', title:'The Mesh class',
    brief:'Implement Mesh (vertex + index buffers, Upload, Draw) and a CreateCube() factory.',
    deliverable:'A Mesh class that draws a cube.' },
  { id:'08-material-system', builds:'Renderer', diff:'Challenge', title:'Shader + Material',
    brief:'Implement a Shader (VS+PS+layout, Bind) and a Material (shader plus color/texture parameters) that binds before drawing.',
    deliverable:'A material system decoupling meshes from shading.' },
  { id:'08-transform-component', builds:'Scene', diff:'Core', title:'The Transform component',
    brief:'Finalize Transform as a component: a local matrix from position/rotation/scale and a world matrix from the hierarchy.',
    deliverable:'The always-present Transform component.' },
  { id:'08-gameobject-system', builds:'Scene', diff:'Challenge', title:'GameObjects & components',
    brief:'Implement GameObject (a Transform plus vector<unique_ptr<Component>>, with AddComponent<T> / GetComponent<T>) and the Component base with virtual Update/Render.',
    deliverable:'The composition core of your engine.' },
  { id:'08-behaviour-scripting', builds:'Scene', diff:'Challenge', title:'Add a MonoBehaviour',
    brief:'Create a Behaviour base class (deriving from Component) with virtual OnStart() and OnUpdate(dt), then write a RotatorBehaviour script and attach it to a GameObject — Unity-style.',
    deliverable:'A Behaviour base + one gameplay script you can drop on any object.' },
  { id:'08-camera-component', builds:'Scene', diff:'Core', title:'The Camera component',
    brief:'Make Camera a Component that yields view + projection from its GameObject\'s Transform; the scene tracks the active camera.',
    deliverable:'A camera that\'s just another component.' },
  { id:'08-engine-loop', builds:'Capstone', diff:'Boss', title:'Assemble MiniEngine',
    brief:'Wire it together: Input.Update → Scene.Update(dt) → Renderer draws every GameObject\'s Mesh + Material with the active Camera → Present. Add a GameObject with a mesh and a Rotator component.',
    deliverable:'A spinning, textured cube rendered by YOUR engine.' },
  { id:'08-where-next', builds:'Capstone', diff:'Challenge', title:'Extend your engine',
    brief:'Pick one extension — basic lighting, a second component, a Dear ImGui panel, or loading an .obj — and add it.',
    deliverable:'MiniEngine, one real feature further.' },

  // Module 09 — Multiplayer & Networking
  { id:'09-networking-basics', builds:'Networking', diff:'Easy', title:'Design your net model',
    brief:'Choose MiniEngine\'s networking model (authoritative client-server over UDP) and list what must be replicated — player Transforms and input.',
    deliverable:'A one-page networking design note.' },
  { id:'09-winsock-setup', builds:'Networking', diff:'Core', title:'Start up Winsock',
    brief:'Initialize Winsock with WSAStartup, create a UDP socket, and link ws2_32.lib — the base of a NetworkSystem.',
    deliverable:'A NetworkSystem that opens (and closes) a socket.' },
  { id:'09-tcp-client-server', builds:'Networking', diff:'Challenge', title:'Echo over TCP',
    brief:'Build a tiny TCP server (bind/listen/accept) and client (connect) that exchange a text message.',
    deliverable:'A working client↔server handshake.' },
  { id:'09-udp-datagrams', builds:'Networking', diff:'Challenge', title:'Send state over UDP',
    brief:'Send and receive a datagram between two instances using a non-blocking UDP socket.',
    deliverable:'Two instances exchanging UDP packets.' },
  { id:'09-serialization', builds:'Networking', diff:'Core', title:'Serialize a Transform',
    brief:'Write a byte-buffer writer/reader and (de)serialize a message id plus a Transform into a packet.',
    deliverable:'Pack/unpack of a game-state packet.' },
  { id:'09-game-networking-model', builds:'Networking', diff:'Challenge', title:'Interpolate remote objects',
    brief:'Buffer incoming snapshots and interpolate a remote object\'s position so its movement looks smooth despite packet timing.',
    deliverable:'Smooth remote-object motion from discrete packets.' },
  { id:'09-engine-networking', builds:'Networking', diff:'Boss', title:'Replicate a GameObject',
    brief:'Add a NetworkSystem to the engine loop that sends the local player\'s Transform each tick and applies received ones to a networked GameObject.',
    deliverable:'Two MiniEngine instances showing each other\'s moving cube.' }
];

(function () {
  window.TASKS_BY_ID = {};
  window.TASKS.forEach(function (t, i) { t.n = i + 1; window.TASKS_BY_ID[t.id] = t; });
  window.TASK_TOTAL = window.TASKS.length;
})();
